version: "3.8"
services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Prueba
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
